print("---Fill these Details---")
name=input("Enter your name: ")
age=int(input("Enter your age: "))
city=input("Enter your City: ")
college=input("Enter your collge name: ")
phone=int(input("Enter yoyr Phone no: "))
print("-------------------------")
print("      STUDENT CARD")
print("-------------------------")
print("Name: "+name)
print("Age: "+str(age))
print("City "+city)
print("College: "+college)
print("Phone: "+str(phone))
print("-------------------------")